<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Be Rewarded this Raya with McD App Spen_f4cdd5</name>
   <tag></tag>
   <elementGuidId>9cb7a487-124c-420e-b376-26c8aa014d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div[2]/div[2]/a[4]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;27 Mar 2025 Try the NEW Ayam Tenders McD™ That spicy, crispy, juicy taste you know and love, now boneless.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3a2be4c-3ff0-45f2-889b-9052027cc771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.mcdonalds.com.my/storage/articles/7979656d753c962037f247430bbdf54e.png</value>
      <webElementGuid>3b774c20-6fd7-4191-9b9d-09915a93cef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>15f1965b-ef26-4b36-9635-e00898bae7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;py-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;flex flex-wrap px-4 mt-4&quot;]/a[@class=&quot;post-preview&quot;]/div[@class=&quot;relative z-10&quot;]/img[@class=&quot;w-full&quot;]</value>
      <webElementGuid>068d13bc-5e4c-4b17-85f5-837e7afec009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div[2]/div[2]/a[4]/div/img</value>
      <webElementGuid>11a66bf3-58ed-44e4-a042-129f5714018d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.mcdonalds.com.my/storage/articles/7979656d753c962037f247430bbdf54e.png')]</value>
      <webElementGuid>50599e32-686f-4d56-9027-0d384bd02cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/img</value>
      <webElementGuid>9fbc584f-2078-40f0-8e70-ce76e43c38f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.mcdonalds.com.my/storage/articles/7979656d753c962037f247430bbdf54e.png']</value>
      <webElementGuid>897f3d78-5d49-4ca7-a6e6-f1db71a6172d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
