<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Drive-Thru</name>
   <tag></tag>
   <elementGuidId>9feb0fc6-a56e-41fc-90ea-3745437aaea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/article/p[4]/strong/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Drive-Thru&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5edd1b2-1d98-47a7-89f3-7df6f9bb6276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mcdonalds.com.my/locate-us</value>
      <webElementGuid>fc9fc7ea-7bda-4578-8df2-3ab375a296e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drive-Thru</value>
      <webElementGuid>f8fa556e-c685-4634-91e2-6a9829da5f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;relative&quot;]/div[@class=&quot;post-body&quot;]/article[@class=&quot;article px-4 text-lg lg:pr-0&quot;]/p[4]/strong[1]/span[1]/a[1]</value>
      <webElementGuid>2dc244ab-4fce-4718-881e-7e60a5b5f109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/article/p[4]/strong/span/a</value>
      <webElementGuid>49149b52-bbdf-4845-b2cf-b618778ae908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Drive-Thru')]</value>
      <webElementGuid>310f4e8e-f74e-4c20-80cc-a9856c9fc4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try the NEW Ayam Tenders McD™'])[2]/following::a[1]</value>
      <webElementGuid>c9cd79a8-3de0-4c39-a98b-cf24eb2d5b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try the NEW Ayam Tenders McD™'])[1]/following::a[1]</value>
      <webElementGuid>e494d4cc-f197-49ff-80af-4b41c62d6135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous Article'])[1]/preceding::a[1]</value>
      <webElementGuid>5bcaf086-a858-474b-bf55-5701a1721c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter The Nether with McNuggets x Minecraft'])[1]/preceding::a[1]</value>
      <webElementGuid>3349373c-87d3-4c8b-b224-444351fc41ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drive-Thru']/parent::*</value>
      <webElementGuid>9762fa3d-74f3-4b20-8c3c-34d40458eb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mcdonalds.com.my/locate-us')]</value>
      <webElementGuid>bec35be2-afed-460c-8c96-faa36047982f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>aeacf628-5966-4ee3-a7d4-e3e1825a65d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mcdonalds.com.my/locate-us' and (text() = 'Drive-Thru' or . = 'Drive-Thru')]</value>
      <webElementGuid>8e43652b-0e30-4991-bb7a-11a96e58fd89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
