<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Locate me_catsIcon</name>
   <tag></tag>
   <elementGuidId>db615ea0-9a15-4674-a76e-c927545b72dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div/div/div[2]/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Breakfast$/ >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7b59e6d-e96f-45a6-9c02-a320a9931479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/locate/ic_breakfast.png</value>
      <webElementGuid>3c645487-eb0e-4888-bbb9-9d24a2023aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catsIcon</value>
      <webElementGuid>8db2eb18-68f4-47bc-b55d-d789ff833c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;post&quot;]/div[@class=&quot;row container larger&quot;]/div[1]/div[@class=&quot;row show-for-medium&quot;]/div[@class=&quot;columns large-12 medium-12 small-12&quot;]/div[@class=&quot;columns small-2&quot;]/img[@class=&quot;catsIcon&quot;]</value>
      <webElementGuid>9c6b45e1-1e0c-446d-b8fb-53e512457ad6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div[3]/img</value>
      <webElementGuid>786a159b-8701-40b9-8158-c3e215ac1e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>9e7b3d79-32f2-495d-979a-2e84cc6af78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/locate/ic_breakfast.png']</value>
      <webElementGuid>2e3c9a31-1fae-46e1-a34e-25d076b09b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
