<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Categories 24 Hours Birthday Par_25a78b</name>
   <tag></tag>
   <elementGuidId>9a50098c-8178-4a38-8c6f-1acb2cbf8ffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categories</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categories']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#categories</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f5b1eb1a-af11-4d3c-ba40-f86a2584aa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categories</value>
      <webElementGuid>c206ea23-f1f3-46b1-a0e5-b58d5395432b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Categories 24 Hours Birthday Party Breakfast Cashless Facility Dessert Center Digital Order Kiosk Drive-Thru Electric Vehicle McCafe McDelivery Surau WiFi</value>
      <webElementGuid>3c045d54-cd57-42be-8460-cfd8527253f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categories&quot;)</value>
      <webElementGuid>6ff7698b-184a-4b13-adfb-93fae209e86d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categories']</value>
      <webElementGuid>ff5d335c-dd82-418b-b889-4e27b150f454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[2]/select</value>
      <webElementGuid>23dd66a2-d3a0-409e-b7d3-dc9cfbd21313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locate Us'])[1]/following::select[2]</value>
      <webElementGuid>393fd446-81c8-4f8a-8f59-ca215d808137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOCATE US'])[1]/following::select[2]</value>
      <webElementGuid>ad5d2d9b-ce1d-4f3d-be21-1976953979d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Now'])[1]/preceding::select[1]</value>
      <webElementGuid>e6ab9cd2-86d5-44d6-ae92-0e6526e1d2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locate me'])[1]/preceding::select[1]</value>
      <webElementGuid>51437cf6-3ac0-41cd-98b8-c710822f883f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>398d7304-9829-46fd-92e1-88172dab843d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categories' and (text() = 'All Categories 24 Hours Birthday Party Breakfast Cashless Facility Dessert Center Digital Order Kiosk Drive-Thru Electric Vehicle McCafe McDelivery Surau WiFi' or . = 'All Categories 24 Hours Birthday Party Breakfast Cashless Facility Dessert Center Digital Order Kiosk Drive-Thru Electric Vehicle McCafe McDelivery Surau WiFi')]</value>
      <webElementGuid>98e2ff89-3fff-4570-862e-0eaec46d5f5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
