<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Johor Kedah Kelantan Kuala Lumpu_383a45</name>
   <tag></tag>
   <elementGuidId>3ce217e9-b94f-4842-8c47-6086862b95cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#states</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='states']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#states</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a86a7f18-52c2-49b4-a8c9-7dd0435292d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>d385fc87-7254-472c-be7a-be59cc1a475c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Johor Kedah Kelantan Kuala Lumpur Labuan Melaka Negeri Sembilan Pahang Pulau Pinang Perak Perlis Putrajaya Sabah Sarawak Selangor Terengganu</value>
      <webElementGuid>b168cb70-759e-4d57-96c5-98707a96f819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;states&quot;)</value>
      <webElementGuid>99534f46-9ee2-4728-aecd-69f68b5791ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='states']</value>
      <webElementGuid>59527f90-8b5a-4adf-8e48-9a022cab4062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div/select</value>
      <webElementGuid>9423165b-03c1-43fa-8931-619ac6dda958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locate Us'])[1]/following::select[1]</value>
      <webElementGuid>8eeade43-df1f-4f0a-91bc-ba11309dc244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOCATE US'])[1]/following::select[1]</value>
      <webElementGuid>b36f21f9-5600-468b-8f5b-580f998628d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Now'])[1]/preceding::select[2]</value>
      <webElementGuid>84ddae49-664c-4b25-9f17-4bcf0f207d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locate me'])[1]/preceding::select[2]</value>
      <webElementGuid>27ca6b1c-5904-4451-9df9-6708dbd37834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dca30e29-2280-4dd6-a517-7b1387fed24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'states' and (text() = 'All Johor Kedah Kelantan Kuala Lumpur Labuan Melaka Negeri Sembilan Pahang Pulau Pinang Perak Perlis Putrajaya Sabah Sarawak Selangor Terengganu' or . = 'All Johor Kedah Kelantan Kuala Lumpur Labuan Melaka Negeri Sembilan Pahang Pulau Pinang Perak Perlis Putrajaya Sabah Sarawak Selangor Terengganu')]</value>
      <webElementGuid>07570c6d-334a-4a27-85d5-19840945c69b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
